In [119]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [120]:
df = pd.read_csv('flipkart_products.csv')

In [121]:
df.sample(5)

,Product Name,Price,Discription,Rating,Page Number
211,Vivo T4 Lite 5G (Titanium Gold 2026) (4GB 64GB),"₹16,999",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB17....,4.3,9
956,"Tecno Pova Curve 2 5G (Storm Titanium, 128 GB)","₹31,999",8 GB RAM | 128 GB ROM17.22 cm (6.78 inch) Full...,4.2,40
792,"OnePlus 13s 5G (Green Silk, 256 GB)","₹57,880",12 GB RAM | 256 GB ROM16.05 cm (6.32 inch) Dis...,4.6,34
54,POCO C71 - Locked with Airtel Prepaid (Desert...,"₹8,999",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB17....,3.8,3
190,"realme Gt 7 (Icesense Black, 512 GB)","₹52,999",12 GB RAM | 512 GB ROM17.22 cm (6.78 inch) Ful...,4.5,8

In [122]:
df.shape

(984, 5)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  984 non-null    object
 1   Price         975 non-null    object
 2   Discription   983 non-null    object
 3   Rating        921 non-null    float64
 4   Page Number   984 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 38.6+ KB

# Data Cleaning and Feature Extraction

In [124]:
# Changing the datatype of Price column from object to float after removing the ₹ symbol and commas

df['Price'] = df['Price'].astype(str).str.replace('₹', '').str.replace(',', '').astype(float)

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  984 non-null    object
 1   Price         975 non-null    float64
 2   Discription   983 non-null    object
 3   Rating        921 non-null    float64
 4   Page Number   984 non-null    int64
dtypes: float64(2), int64(1), object(2)
memory usage: 38.6+ KB

In [126]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Price,975.0,24418.155897,23311.686516,106.0,8995.0,17999.0,33248.5,189999.0
Rating,921.0,4.150489,0.359048,2.3,4.1,4.2,4.4,5.0
Page Number,984.0,21.000000,11.838176,1.0,11.0,21.0,31.0,41.0

In [127]:
# Permanently removes all rows where Price is less than 999

df[df['Price'] < 999].sort_values(by='Price', ascending=False).head(10)
df = df[df['Price'] >= 999]

In [128]:
df.sample(5)

,Product Name,Price,Discription,Rating,Page Number
652,"REDMI Note 15 5G (Glacier Blue, 256 GB)",34899.0,8 GB RAM | 256 GB ROM17.2 cm (6.77 inch) Displ...,4.4,28
930,"POCO X8 Pro Max (Blue, 512 GB)",52999.0,12 GB RAM | 512 GB ROM17.35 cm (6.83 inch) Ful...,4.5,39
486,"Micromax Vdeo 2 (Champagne, 8 GB)",6249.0,1 GB RAM | 8 GB ROM | Expandable Upto 32 GB11....,3.8,21
707,"REDMI Note 15 5G (Mist Purple, 128 GB)",28795.0,8 GB RAM | 128 GB ROM17.2 cm (6.77 inch) Displ...,4.4,30
600,"Infinix Note edge (Lunar Titanium, 128 GB)",23999.0,8 GB RAM | 128 GB ROM17.22 cm (6.78 inch) Full...,4.3,26

In [129]:
df.isnull().sum()

Product Name     0
Price            0
Discription      0
Rating          27
Page Number      0
dtype: int64

In [130]:
missing_prices = df[df['Price'].isnull()]
missing_prices

Empty DataFrame
Columns: [Product Name, Price, Discription, Rating, Page Number]
Index: []

In [131]:
# Extract RAM (matches numbers followed by MB or GB before the word RAM)
df['RAM'] = df['Discription'].str.extract(r'(\d+\s*[MG]B)\s*RAM')

# Extract ROM (matches numbers followed by MB or GB before the word ROM)
df['ROM'] = df['Discription'].str.extract(r'(\d+\s*[MG]B)\s*ROM')
df.sample(5)

,Product Name,Price,Discription,Rating,Page Number,RAM,ROM
793,"REDMI Note-14 Pro 5G (Ivy Green, 256 GB)",27374.0,8 GB RAM | 256 GB ROM16.94 cm (6.67 inch) Disp...,4.3,34,8 GB,256 GB
583,REDMI A5 - Locked with Airtel Prepaid (Pondic...,8995.0,3 GB RAM | 64 GB ROM | Expandable Upto 2 TB17....,4.1,25,3 GB,64 GB
229,"realme Narzo 90x 5G (Aqua Blue, 128 GB)",19000.0,4 GB RAM | 128 GB ROM17.27 cm (6.8 inch) HD+ D...,4.0,10,4 GB,128 GB
972,"vivo Y21 5G (Straw Gold, 64 GB)",20999.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB17....,4.2,41,4 GB,64 GB
100,"POCO C61 (Diamond Dust Black, 64 GB)",7299.0,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB17....,4.1,5,4 GB,64 GB

In [132]:
# Create a table showing only rows where the 'ROM' column is missing (NaN)
missing_rom_df = df[df['RAM'].isna()]

# Display the table
missing_rom_df
# They don't have RAM mentioned.

,Product Name,Price,Discription,Rating,Page Number,RAM,ROM
218,"Apple iPhone 16 Plus (White, 128 GB)",79900.0,128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,4.6,10,NaN,128 GB
290,"Apple iPhone 16 Plus (Ultramarine, 128 GB)",79900.0,128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,4.6,13,NaN,128 GB
639,"Apple iPhone 16e (White, 256 GB)",69900.0,256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.5,27,NaN,256 GB
653,"Apple iPhone 16e (White, 256 GB)",69900.0,256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.5,28,NaN,256 GB
656,"Apple iPhone 16 (Teal, 128 GB)",69900.0,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,28,NaN,128 GB
752,"Apple iPhone 16e (Black, 128 GB)",59900.0,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.5,32,NaN,128 GB
846,"Apple iPhone 16 (Ultramarine, 128 GB)",69900.0,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,36,NaN,128 GB

In [133]:
df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [134]:
df.isnull().sum()

Product Name    0
Price           0
Discription     0
Rating          0
Page Number     0
RAM             7
ROM             0
dtype: int64

# EDA